import type { MetadataRoute } from "next";

/**
 * The web app manifest — what lets Graphiq be installed, and what it looks like
 * once it is.
 *
 * The point is space. Installed, the browser's ~110px of URL bar and toolbar
 * goes away and the editor gets it; without a manifest there is no install, and
 * a phone spends an eighth of its screen on chrome that belongs to something
 * else. Everything here is metadata — no service worker, no caching, nothing
 * that could serve a stale build. (A service worker is NOT required to be
 * installable; it is required for Chrome's `beforeinstallprompt`, which is a
 * separate decision recorded in TODO M5.)
 *
 * `display_override` is a preference list tried before `display`. Deliberately
 * NOT including `window-controls-overlay`: it hands the title-bar strip to the
 * page, and a page that does not read `titlebarAreaRect` gets the OS window
 * controls drawn straight over its own top bar. Asking for a mode the app does
 * not implement is worse than not asking.
 *
 * `fullscreen` is left out for the same kind of reason from the other side: it
 * removes the status bar, which zeroes `safe-area-inset-top` and undoes the
 * notch handling the shell is built around. Standalone keeps the status bar and
 * the insets that describe it.
 *
 * Next serves this at `/manifest.webmanifest` and links it from every page.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    /* A stable identity, so a later change of `start_url` does not read as a
       different app and orphan the installed copy. */
    id: "/",
    name: "Graphiq Studio — Photo Editor",
    short_name: "Graphiq",
    description:
      "A full-featured, non-destructive raster image editor that runs entirely in your browser. No account, no upload, no server.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    display_override: ["standalone", "minimal-ui", "browser"],
    /* The dark theme's `--bg`. This is the splash ground while the app boots,
       so it matches the launcher icon's ground rather than flashing white. */
    background_color: "#18191a",
    theme_color: "#18191a",
    orientation: "any",
    lang: "en",
    dir: "ltr",
    categories: ["graphics", "photo", "productivity"],
    icons: [
      /* `any` and `maskable` are separate PURPOSES, not sizes, and a platform
         picks by purpose first. Declaring one icon as both is the common
         shortcut and it is wrong twice over: an edge-to-edge glyph loses its
         wingtips to the shape mask, and a padded one floats small and lost
         where no mask is applied. Two families, generated by
         tools/build-pwa-icons.js. */
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
